### ISSUE TITLE
Add load/unload BPF program API

### ISSUE THREAD

**Issue by mtcherni95** [aquasecurity/libbpfgo#106]
We would like to have the capability to load and unload BPF program in runtime.
For the `Unload` API we could use the libbpf `bpf_program__unload` (https://github.com/libbpf/libbpf/blob/master/src/libbpf.h#L369). Some open questions here that I would like to share:
1. if the program is attached, should we first detach it? in that case, we should add this capability as well (detaching BPF programs)
2. if the program is a link, should we remove it from `Module.links`? do we also handle the link removal from libbpf prospective?

Now, regarding the `Load` API, we could use the libbpf function `bpf_prog_load `  (https://github.com/libbpf/libbpf/blob/master/src/bpf.h#L144), however for that we should wait till we adopt libbpfv0.6.0.

FYI @grantseltzer @rafaeldtinoco

**Comment by yanivagman** [comment]
For some reason `bpf_program__load` was deprecated by libbpf, saying that bpf_object__load() should be used instead.
However, using bpf_object__load() doesn't fit for our usecase as we already loaded the bpf object, and want to dynamically load/unload programs from this bpf object.
Also, the problem with bpf_prog_load function is that it doesn't use struct bpf_program as an argument, but expects the program as raw instructions. As you can see, it is defined in bpf.h (which is the low level syscall API) and not in libbpf.h. 
Maybe the API was deprecated because they didn't thought someone might want to load/unload/load... programs in runtime? We can ask that question in the libbpf mailing list.

**Comment by mtcherni95** [comment]
Yeah, I agree that we should check with them. From the other side, we could create a higher level API for `Load` that under the hood uses the low level `bpf_prog_load`, even that this would require more work from our side in order to create the abstraction.

**Comment by yanivagman** [comment]
These APIs were indeed deprecated.
See the answer I got from Andrii in the mailing list:
https://lore.kernel.org/bpf/CAMy7=ZW60WmV5R9myXCzrZGZXMrPhO+dwaW8+aABUJO9pMV+yA@mail.gmail.com/

We should load all programs at start, and attach/destroy links as required.
