### ISSUE TITLE
(*BPFMap) GetValue return unexpected value when using BPF_MAP_TYPE_PERCPU_ARRAY

### ISSUE THREAD

**Issue by wgblikeW** [aquasecurity/libbpfgo#191]
Recently, I am learning BPF programming from taking the lecture in xdp-tutorial repository. In the kernel side program, I have created the Map in `BPF_MAP_TYPE_PERCPU_ARRAY` type and updated the value without atomic operation.

``` C
    rec = bpf_map_lookup_elem(&xdp_stats_map_percpu, &key);
    if (!rec)
        return XDP_ABORTED;

    rec->rx_packets += 1;
    rec->byte_counters += data_end - data;
```

And I looked for the value in the map with `(*BPFMap) GetValue()` function, but I got unexpected value. When I went deeply into the code, I realized `(*BPFMap) GetValue()` just return part of the data.

If we just using libbpf in userspace side, the implementation will be like,

``` C
    struct datarec values[nr_cpus];

    if ((bpf_map_lookup_elem(fd, &key, values)) != 0) {
	fprintf(stderr,
	    "ERR: bpf_map_lookup_elem failed key:0x%X\n", key);
	return;
    }

    /* Sum values from each CPU */
    for (i = 0; i < nr_cpus; i++) {
	sum_pkts  += values[i].rx_packets;
	sum_bytes += values[i].rx_bytes;
    }
```

So I implemented my own `GetValue` function,

``` Go
func (b *myBPFMap) GetValuePerCPU(key unsafe.Pointer) ([]byte, error) {
	value := make([]byte, b.ValueSize()*runtime.NumCPU())
	valuePtr := unsafe.Pointer(&value[0])

	ret, errC := C.bpf_map_lookup_elem(C.int(b.GetFd()), key, valuePtr)
	if ret != 0 {
		return nil, fmt.Errorf("failed to lookup value %v in map %s: %w", key, b.GetName(), errC)
	}

	return value, nil
}
```

And finally I got what I expected. 

Does we need to a new method to obtain what I have mentioned above, or I have missed something critical. 

Thanks for your answers.

**Comment by rafaeldtinoco** [comment]
> The variable num_cpu was parsed from the file /sys/devices/system/cpu/possible, which is 0-127 in my case, but my presented CPUs are 8.

I think I see your point. This part was tackled by @grantseltzer but he is off this and next week.

Here is an example on how we read that file in tracee:
 https://github.com/aquasecurity/tracee/blob/00c0de0099bf9fb0802971f44a42861775c66973/pkg/utils/environment/amount_cpus.go#L1

> Note it has a special syntax for enabled CPUs versus disabled ones.

With that said, 

It is complicated to use `runtime.NumCPU()` value like you did: Imagine you have 32 CPUs in your system, and enabled to your runtime CPUs 0, 4,5,6,12,14 (either because you're in a cgroup cpuset or because you simply disabled the others). 

How would you know which per-cpu buffer to read for the CPUs you have online ?

If you use `runtime.NumCPU()` your logic will get values 0-7, but your online cpus are different. Thus the need to read all of them, no ?

Let me know if not =D.

**Comment by wgblikeW** [comment]
That makes sense. I just confuse about where does the kernel get this value (`/sys/devices/system/cpu/possible`) from, since my hardware platform can't be supported that CPUs. By the way, I am running `Linux 5.15.0-41-generic #44-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux` on VM with 8 CPUs settings. The "**possible_cpus**" seems much more larger. Anyway this issue's major topic is solved, I will close this issue soon.

Appreciated. @rafaeldtinoco
