### ISSUE TITLE
BTF: support providing external kconfig

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/libbpfgo#61]
When running libbpf in an environment where BTF is enabled, it requires having kconfig data which is read from either `/proc/config.gz `or `/boot/config-xxx`.
When working from a container in an environment where kconfig is located under /boot and it is not mounted, libbpf might fail to load the BPF object. To avoid this situation, we can expand libbpfgo to support providing extra kconfig values and give it as an argument to libbpf. See https://github.com/libbpf/libbpf/blob/master/src/libbpf.h#L96

**Comment by rafaeldtinoco** [comment]
I recently changed KernelConfig in libbpfgo. There is a regression for /proc/config.gz (happening in archlinux) for that version. I'll fix that and work in this issue together:

https://github.com/aquasecurity/libbpfgo/pull/57
and
https://github.com/aquasecurity/libbpfgo/pull/58

**Comment by rafaeldtinoco** [comment]
@yanivagman I'm almost done with the changes that allows us to specify KCONFIG and OSRELEASE files through environment. I think they're nice BUT wanted to inform you that libbpf still complains about the missing kconfig file because it loads both: the given kconfig and the system kconfig. Given kconfig is not meant to replace the system one (we might need to propose a change to them):

```C
	if (need_config && extra_kconfig) {
	    fprintf(stdout, "TEMPORARY 02: %s\n", extra_kconfig);
		err = bpf_object__read_kconfig_mem(obj, extra_kconfig, kcfg_data);
		if (err)
			return -EINVAL;
		need_config = false;
		for (i = 0; i < obj->nr_extern; i++) {
			ext = &obj->externs[i];
			if (ext->type == EXT_KCFG && !ext->is_set) {
				need_config = true;
				break;
			}
		}
	}
	if (need_config) {
		err = bpf_object__read_kconfig_file(obj, kcfg_data);
		if (err)
			return -EINVAL;
	}
```

my output:

```
$ sudo TRACEE_KCONFIG_FILE=/boot/config-5.14.0-rc5+.orig TRACEE_OSRELEASE_FILE=/etc/os-release.orig ./dist/tracee-ebpf --debug --trace uid=1000 --trace pid=new --trace event=execve --trace event=cap_capable --output option:detect-syscall
OSInfo: VERSION: "21.10 (Impish Indri)"
OSInfo: VERSION_CODENAME: impish
OSInfo: ID: ubuntu
OSInfo: ID_LIKE: debian
OSInfo: KERNEL_RELEASE: 5.14.0-rc5+
OSInfo: PRETTY_NAME: "Ubuntu Impish Indri (development branch)"
OSInfo: VERSION_ID: "21.10"
BTF: bpfenv = false, btfenv = false, vmlinux = true
BPF: using embedded BPF object
unpacked CO:RE bpf object file into memory
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
AGORA:  /boot/config-5.14.0-rc5+.orig
TEMPORARY: /boot/config-5.14.0-rc5+.orig
TEMPORARY 02: /boot/config-5.14.0-rc5+.orig
libbpf: failed to open system Kconfig
libbpf: failed to load object 'embedded-core'
2021/09/02 04:03:25 error creating Tracee: failed to load BPF object
```

**Comment by rafaeldtinoco** [comment]
@yanivagman I'm almost done with the changes that allows us to specify KCONFIG and OSRELEASE files through environment. I think they're well done so far... BUT wanted to inform you that libbpf still complains about the missing kconfig file because it loads both: the given kconfig and the system kconfig.

Given kconfig is not meant to replace the system one (we might need to propose a change to them). The system one is the one it uses to resolve the kconfig externs (`need_config = true` is back again after `extra_kconfig` is read)

```C
	if (need_config && extra_kconfig) {
	    fprintf(stdout, "TEMPORARY 02: %s\n", extra_kconfig);
		err = bpf_object__read_kconfig_mem(obj, extra_kconfig, kcfg_data);
		if (err)
			return -EINVAL;
		need_config = false;
		for (i = 0; i < obj->nr_extern; i++) {
			ext = &obj->externs[i];
			if (ext->type == EXT_KCFG && !ext->is_set) {
				need_config = true;
				break;
			}
		}
	}
	if (need_config) {
		err = bpf_object__read_kconfig_file(obj, kcfg_data);
		if (err)
			return -EINVAL;
	}
```

The output:

```
$ sudo TRACEE_KCONFIG_FILE=/boot/config-5.14.0-rc5+.orig TRACEE_OSRELEASE_FILE=/etc/os-release.orig ./dist/tracee-ebpf --debug --trace uid=1000 --trace pid=new --trace event=execve --trace event=cap_capable --output option:detect-syscall
OSInfo: VERSION: "21.10 (Impish Indri)"
OSInfo: VERSION_CODENAME: impish
OSInfo: ID: ubuntu
OSInfo: ID_LIKE: debian
OSInfo: KERNEL_RELEASE: 5.14.0-rc5+
OSInfo: PRETTY_NAME: "Ubuntu Impish Indri (development branch)"
OSInfo: VERSION_ID: "21.10"
BTF: bpfenv = false, btfenv = false, vmlinux = true
BPF: using embedded BPF object
unpacked CO:RE bpf object file into memory
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
AGORA:  /boot/config-5.14.0-rc5+.orig
TEMPORARY: /boot/config-5.14.0-rc5+.orig
TEMPORARY 02: /boot/config-5.14.0-rc5+.orig
libbpf: failed to open system Kconfig
libbpf: failed to load object 'embedded-core'
2021/09/02 04:03:25 error creating Tracee: failed to load BPF object
```

I don't currently believe they will accept getting rid of the system kconfig - as it does not make sense for general terms, only for our privileged container case, which could mitigate this by simply bind mounting the kconfig file.

If I create an empty /boot/config-$(uname -r) while passing all real kconfig through ENV variable file:

```
unpacked CO:RE bpf object file into memory
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
AGORA:  /boot/config-5.14.0-rc5+.orig
TEMPORARY: /boot/config-5.14.0-rc5+.orig
TEMPORARY 02: /boot/config-5.14.0-rc5+.orig
libbpf: extern CONFIG_ARCH_HAS_SYSCALL_WRAPPER (strong) not resolved
libbpf: failed to load object 'embedded-core'
2021/09/02 04:08:51 error creating Tracee: failed to load BPF object
```

> The relocations are to be done by the system kconfig as libbpf is currently programmed now.

**Comment by rafaeldtinoco** [comment]
NOTE: I'll propose my PRs for libbpfgo and tracee mitigating this by creating a system kconfig file from the given environment file if that does not exist. That will be the easiest way to solve this issue without libbpf upstream modifications (or locally maintained patches).

**Comment by rafaeldtinoco** [comment]
For the scenario above, I have opened and closed 2 PRs:

- https://github.com/aquasecurity/libbpfgo/pull/68
- https://github.com/aquasecurity/tracee/pull/985

Just so you could have a reference why this approach would not work.

Now, because we only need CONFIG_ARCH_HAS_SYSCALL_WRAPPER, we should get rid of the 'kconfig extern' logic from libbpf and export the CONFIG_ARCH_HAS_SYSCALL_WRAPPER value within our config map OR a new kconfig map. This would allow us to use overridden kconfig file for tracee/libbpfgo AND make libbpf to ignore its need.

**Comment by rafaeldtinoco** [comment]
If you agree to that approach I can change this actual code to do that, and also use the good changes of it like improving os-release and kconfig handling. WDYT ?

**Comment by yanivagman** [comment]
@rafaeldtinoco doesn't #67 resolves this as well?

**Comment by rafaeldtinoco** [comment]
@yanivagman not yet.. Im sending a PR for this one shortly.

**Comment by rafaeldtinoco** [comment]
For the PR Im sending ,the tests are:

When no kconfig NOR os-release files were found (you can see it assumed CONFIG_ARCH_HAS_SYSCALL_WRAPPER was 0 a it had no clue):

```
$ sudo ./dist/tracee-ebpf --debug --trace uid=1000 --trace pid=new --trace event=execve --trace event=cap_capable --output option:detect-syscall
KConfig: warning: could not check enabled kconfig features
(could not read /boot/config-5.14.0-rc5+: stat /boot/config-5.14.0-rc5+: no such file or directory)
OSInfo: KERNEL_RELEASE: 5.14.0-rc5+
OSInfo: warning: os-release file could be found
(open /etc/os-release: no such file or directory)
BTF: bpfenv = false, btfenv = false, vmlinux = true
BPF: using embedded BPF object
unpacked CO:RE bpf object file into memory
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
05:08:54:046452  1000   bash             9806    9806    0                execve               pathname:  , argv: []

End of events stream
Stats: {EventCount:1 ErrorCount:0 LostEvCount:0 LostWrCount:0 LostNtCount:0}
```

But if you inform a kconfig file it will get the value from it:

```
$ sudo LIBBPFGO_KCONFIG_FILE=/boot/config-5.14.0-rc5+.orig ./dist/tracee-ebpf --debug --trace uid=1000 --trace pid=new --trace event=execve --trace event=cap_capable --output option:detect-syscall
OSInfo: KERNEL_RELEASE: 5.14.0-rc5+
OSInfo: warning: os-release file could be found
(open /etc/os-release: no such file or directory)
BTF: bpfenv = false, btfenv = false, vmlinux = true
BPF: using embedded BPF object
unpacked CO:RE bpf object file into memory
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
05:09:45:147632  1000   bash             9852    9852    0                execve               pathname: /bin/ls, argv: [ls --color=auto]

End of events stream
Stats: {EventCount:1 ErrorCount:0 LostEvCount:0 LostWrCount:0 LostNtCount:0}
```

NOTE: libbpf does not need kconfig any longer.
