### ISSUE TITLE
GetOsInfo API when run in container returns container info and not host info 

### ISSUE THREAD

**Issue by mtcherni95** [aquasecurity/libbpfgo#92]
The GetOsInfo should return the host info even when used inside container execution.
A first approach, as suggested by @yanivagman , would be to read at /proc/1/root/etc/os-release instead of /etc/os-release. 
However this will require: 
1. running container with --pid=host
2. privileges

**Comment by rafaeldtinoco** [comment]
I think we've discussed this in the past and it resulted in the following documentation: 

https://github.com/aquasecurity/libbpfgo/blob/main/docs/helpers.md

Could you check if that addresses the issue ?

> In the past we agreed that we would create a mocked os-release file based on the host information IF we chose not to simply bind mount the /etc/os-release as /etc/os-release-host inside the container, for example.

**Comment by mtcherni95** [comment]
For sure pointing to host os-release via env var LIBBPFGO_OSRELEASE_FILE will solve the issue. From the other side I am not sure how ideal this actually is as it relies on the user to expose the env var.

**Comment by rafaeldtinoco** [comment]
I'll address this concern - to run the container without the need to set environment variables, and, yet, making sure osrelease (mocked or real) is exposed to the container - together with the BTFhub support PR (https://github.com/aquasecurity/tracee/pull/1125)

**Comment by rafaeldtinoco** [comment]
@danielpacak for you to catch up when you can:

This is one of the needs to be addressed to support BTFhub, in parallel to the CO-RE fixes, that can be addressed at: https://github.com/aquasecurity/tracee/pull/1125#discussion_r749520121.

Like we discussed, about having the container generated correctly, we will have to "mock" the /etc/os-release file (like described at: https://github.com/aquasecurity/libbpfgo/blob/main/docs/helpers.md) so that docker container won't depend in /etc/os-release file from the container (it has to be based on hosts /etc/os-release file).

**Comment by rafaeldtinoco** [comment]
I don't think this is something we should target. The environment variable was created to override the `/etc/os-release` file being searched and it serves its purpose. Tracee uses like that, we should close this for now.
